### ISSUE TITLE
Passing pointer to out of scope local variable

### ISSUE THREAD

**Issue by akohlmey** [MolSSI-MDI/MDI_Library#158]
https://github.com/MolSSI-MDI/MDI_Library/blob/54a477c3ab067384916059b5cc8b881b24babeff/MDI_Library/mdi.c#L2126

This piece of code is problematic since it creates a pointer to a local variable (allocated on the stack) and passes it to a function after the stack frame has been released. It can only work by chance. Here is the info from Coverity scan static code analysis.

![mpi-comm-convert](https://github.com/MolSSI-MDI/MDI_Library/assets/289251/63dae46b-f3ee-4859-89d7-5257980fc859)

**Comment by taylor-a-barnes** [comment]
Thanks very much for pointing this out Axel.  This should be resolved by commit 6760fd2.

**Comment by taylor-a-barnes** [comment]
Thanks again!  The [v1.4.26](https://github.com/MolSSI-MDI/MDI_Library/releases/tag/v1.4.26) release includes this fix.
